spigot:
  container_name: satoshiquest
  build: .
  volumes:
    - "./world:/spigot/world"
    - "./world_nether:/spigot/world_nether"
    - "./world_the_end:/spigot/world_the_end"
    - "/SatoshiQuest/spigot/SatoshiQuest:/spigot/SatoshiQuest"
    - "/SatoshiQuest/spigot/SatoshiQuest_nether:/spigot/SatoshiQuest_nether"
    - "/SatoshiQuest/spigot/SatoshiQuest_the_end:/spigot/SatoshiQuest_the_end"
    - "./target/SatoshiQuest.jar:/spigot/plugins/SatoshiQuest.jar"
  ports:
    - "25566:25566"
  env_file:
    - variables.env
  environment:
    - SATOSHIQUEST_ENV=development
    - BUYIN_AMOUNT=1.00
    - LIVES_PERBUYIN=1
    - ADDRESS_URL=https://www.blockchain.com/btc/address/
  links:
    - redis
redis:
  image: redis
