api-version: 1.13
name: SatoshiQuest
version: 1.0
author: The SatoshiQuest Dev Team
main: com.satoshiquest.satoshiquest.SatoshiQuest
description: The SatoshiQuest Open Source Project
commands:
  ban:
    description: "Adds player to the ban list"
    usage: "/ban <player>"
  banlist:
    description: "Prints the list of banned players"
    usage: "/banlist"
  home:
    description: "teleports you to your last bed"
    usage: "/home"
  maintenance:
    description: "Enables maintenance mode and stops players from joining the server"
    usage: "/maintenance <seconds>"
  mod:
    description: "Utility to add/remove/list moderators"
    usage: "/mod <add|remove|list>"
  motd:
    description: "Change the message of the day"
    usage: "/motd <message>"
  spectate:
    description: "Allows moderators to spectate players' actions"
    usage: "/spectate <player>"
  unban:
    description: "Removes player from the ban list"
    usage: "/unban <player>"
  emergencystop:
    description: "Stops the server cleanly in case of emergency"
    usage: "/emergencystop [reason]"
  wallet:
    description: "Displays your SatoshiQuest wallet info"
    usage: "/wallet"
  crashtest:
    description: "Crashes the plugin on purpose, hell breaks loose. Don't try this at home"
    usage: "/crashtest"
  report:
    description: "Sends a report message to the moderators"
    usage: "/report <player> <reason>"
